noinst_LTLIBRARIES = libksvgdom.la

myincludedir = $(includedir)/dom
myinclude_HEADERS = SVGAElement.h SVGAltGlyphElement.h SVGAltGlyphDefElement.h SVGGlyphRefElement.h SVGAngle.h SVGAnimateColorElement.h SVGAnimateElement.h \
					SVGAnimateMotionElement.h SVGAnimateTransformElement.h SVGAnimatedAngle.h SVGAnimatedBoolean.h \
					SVGAnimatedEnumeration.h SVGAnimatedInteger.h SVGAnimatedLength.h SVGAnimatedLengthList.h \
					SVGAnimatedNumber.h SVGAnimatedNumberList.h SVGAnimatedPathData.h SVGAnimatedPoints.h \
					SVGAnimatedPreserveAspectRatio.h SVGAnimatedRect.h SVGAnimatedString.h SVGAnimatedTransformList.h \
					SVGAnimationElement.h SVGCSSRule.h  SVGCircleElement.h  SVGClipPathElement.h SVGColor.h \
					SVGColorProfileElement.h SVGColorProfileRule.h SVGComponentTransferFunctionElement.h SVGCursorElement.h \
					SVGDefinitionSrcElement.h SVGDefsElement.h SVGDescElement.h SVGDocument.h SVGElement.h SVGElementInstance.h \
					SVGElementInstanceList.h SVGEllipseElement.h SVGEvent.h SVGException.h SVGExternalResourcesRequired.h \
					SVGFEBlendElement.h SVGFEColorMatrixElement.h SVGFEComponentTransferElement.h SVGFECompositeElement.h \
					SVGFEConvolveMatrixElement.h SVGFEDiffuseLightingElement.h SVGFEDisplacementMapElement.h SVGFEDistantLightElement.h \
					SVGFEFloodElement.h SVGFEFuncAElement.h SVGFEFuncBElement.h SVGFEFuncGElement.h SVGFEFuncRElement.h \
					SVGFEGaussianBlurElement.h SVGFEImageElement.h SVGFEMergeElement.h SVGFEMergeNodeElement.h SVGFEMorphologyElement.h \
					SVGFEOffsetElement.h SVGFEPointLightElement.h SVGFESpecularLightingElement.h SVGFESpotLightElement.h \
					SVGFETileElement.h SVGFETurbulenceElement.h SVGFilterElement.h SVGFilterPrimitiveStandardAttributes.h \
					SVGFitToViewBox.h SVGFontElement.h SVGFontFaceElement.h SVGFontFaceFormatElement.h SVGFontFaceNameElement.h \
					SVGFontFaceSrcElement.h SVGFontFaceUriElement.h SVGForeignObjectElement.h SVGGElement.h SVGGlyphElement.h \
					SVGGradientElement.h SVGHKernElement.h SVGICCColor.h SVGImageElement.h SVGLangSpace.h SVGLength.h SVGLengthList.h \
					SVGLineElement.h SVGLinearGradientElement.h SVGLocatable.h SVGMPathElement.h SVGMarkerElement.h SVGMaskElement.h \
					SVGMatrix.h SVGMetadataElement.h SVGMissingGlyphElement.h SVGNumber.h SVGNumberList.h SVGPaint.h SVGPathElement.h \
					SVGPathSeg.h SVGPathSegArc.h SVGPathSegClosePath.h SVGPathSegCurvetoCubic.h SVGPathSegCurvetoCubicSmooth.h \
					SVGPathSegCurvetoQuadratic.h SVGPathSegCurvetoQuadraticSmooth.h SVGPathSegLineto.h SVGPathSegLinetoHorizontal.h \
					SVGPathSegLinetoVertical.h SVGPathSegList.h SVGPathSegMoveto.h SVGPatternElement.h SVGPoint.h SVGPointList.h \
					SVGPolygonElement.h SVGPolylineElement.h SVGPreserveAspectRatio.h SVGRadialGradientElement.h SVGRect.h \
					SVGRectElement.h SVGRenderingIntent.h SVGSVGElement.h SVGScriptElement.h SVGSetElement.h SVGStopElement.h \
					SVGStringList.h SVGStylable.h SVGStyleElement.h SVGSwitchElement.h SVGSymbolElement.h SVGTRefElement.h \
					SVGTSpanElement.h SVGTests.h SVGTextContentElement.h SVGTextElement.h SVGTextPathElement.h SVGTextPositioningElement.h \
					SVGTitleElement.h SVGTransform.h SVGTransformList.h SVGTransformable.h SVGURIReference.h SVGUnitTypes.h \
					SVGUseElement.h SVGVKernElement.h SVGViewElement.h SVGViewSpec.h SVGWindow.h SVGZoomAndPan.h SVGZoomEvent.h

libksvgdom_la_SOURCES = SVGLength.cpp SVGAnimatedLength.cpp SVGNumber.cpp SVGAnimatedNumber.cpp SVGPoint.cpp SVGTSpanElement.cpp SVGTRefElement.cpp \
						SVGAnimatedLengthList.cpp SVGAnimatedNumberList.cpp SVGTransformList.cpp SVGAElement.cpp SVGAnimatedTransformList.cpp \
						SVGRectElement.cpp SVGCircleElement.cpp SVGEllipseElement.cpp SVGLineElement.cpp SVGPolylineElement.cpp SVGPolygonElement.cpp \
						SVGTextPositioningElement.cpp SVGTextContentElement.cpp SVGTextElement.cpp SVGImageElement.cpp SVGUseElement.cpp \
						SVGMatrix.cpp SVGTransform.cpp SVGPointList.cpp SVGDocument.cpp SVGAnimatedEnumeration.cpp SVGDefsElement.cpp \
						SVGLocatable.cpp SVGTransformable.cpp SVGStylable.cpp SVGGElement.cpp SVGAngle.cpp SVGAnimatedAngle.cpp \
						SVGColor.cpp SVGPathElement.cpp SVGPathSegList.cpp SVGTests.cpp SVGLangSpace.cpp SVGStringList.cpp \
						SVGPathSeg.cpp SVGPathSegClosePath.cpp SVGPathSegMoveto.cpp SVGPathSegLinetoHorizontal.cpp SVGPathSegLinetoVertical.cpp SVGPathSegLineto.cpp \
						SVGPathSegCurvetoCubic.cpp SVGDescElement.cpp SVGTitleElement.cpp SVGExternalResourcesRequired.cpp SVGAnimatedBoolean.cpp SVGNumberList.cpp \
						SVGPathSegCurvetoCubicSmooth.cpp SVGPathSegCurvetoQuadratic.cpp SVGAnimatedRect.cpp SVGAnimatedString.cpp \
						SVGPathSegCurvetoQuadraticSmooth.cpp SVGPathSegArc.cpp SVGURIReference.cpp SVGAnimatedInteger.cpp SVGLengthList.cpp \
						SVGSVGElement.cpp SVGRect.cpp SVGFitToViewBox.cpp SVGAnimatedPreserveAspectRatio.cpp SVGPreserveAspectRatio.cpp SVGElement.cpp \
						SVGStyleElement.cpp SVGClipPathElement.cpp SVGMaskElement.cpp SVGColorProfileElement.cpp SVGColorProfileRule.cpp SVGZoomAndPan.cpp SVGScriptElement.cpp \
						SVGSwitchElement.cpp SVGSymbolElement.cpp \
						SVGDefinitionSrcElement.cpp SVGFontFaceElement.cpp SVGFontFaceFormatElement.cpp SVGFontFaceNameElement.cpp SVGFontFaceSrcElement.cpp SVGHKernElement.cpp SVGMetadataElement.cpp SVGVKernElement.cpp SVGCursorElement.cpp SVGForeignObjectElement.cpp SVGFontFaceUriElement.cpp \
						SVGElementInstance.cpp SVGElementInstanceList.cpp SVGAnimatedPoints.cpp SVGAnimatedPathData.cpp SVGMarkerElement.cpp SVGViewSpec.cpp SVGViewElement.cpp \
						SVGFilterElement.cpp SVGFilterPrimitiveStandardAttributes.cpp SVGFEBlendElement.cpp SVGFEColorMatrixElement.cpp SVGFEComponentTransferElement.cpp SVGComponentTransferFunctionElement.cpp SVGFEFuncAElement.cpp SVGFEFuncBElement.cpp SVGFEFuncGElement.cpp SVGFEFuncRElement.cpp SVGFECompositeElement.cpp SVGFEConvolveMatrixElement.cpp SVGFEFloodElement.cpp SVGFEGaussianBlurElement.cpp SVGFEDiffuseLightingElement.cpp SVGFEDistantLightElement.cpp SVGFEPointLightElement.cpp SVGFESpotLightElement.cpp SVGFEDisplacementMapElement.cpp SVGFEMergeElement.cpp SVGFEMergeNodeElement.cpp SVGFEImageElement.cpp SVGFEMorphologyElement.cpp SVGFEOffsetElement.cpp SVGFESpecularLightingElement.cpp SVGFETileElement.cpp SVGFETurbulenceElement.cpp  \
						SVGAnimationElement.cpp SVGAnimateElement.cpp SVGSetElement.cpp SVGAnimateMotionElement.cpp SVGAnimateColorElement.cpp SVGAnimateTransformElement.cpp \
						SVGEvent.cpp SVGZoomEvent.cpp SVGICCColor.cpp SVGCSSRule.cpp \
						SVGGradientElement.cpp SVGRadialGradientElement.cpp SVGLinearGradientElement.cpp SVGStopElement.cpp SVGPatternElement.cpp SVGMPathElement.cpp \
						SVGFontElement.cpp SVGAltGlyphElement.cpp SVGGlyphRefElement.cpp SVGAltGlyphDefElement.cpp SVGGlyphElement.cpp SVGMissingGlyphElement.cpp SVGPaint.cpp SVGTextPathElement.cpp SVGWindow.cpp

libksvgdom_la_METASOURCES = AUTO

INCLUDES = -I$(top_srcdir)/ksvg/core -I$(top_srcdir)/ksvg/ecma -I$(top_srcdir)/ksvg/impl -I$(top_srcdir)/ksvg/impl/libs/libtext2path/src -I$(top_srcdir)/impl/ $(all_includes)
