INCLUDES = -I$(srcdir)/.. -I$(srcdir)/../fofi -I$(srcdir)/../goo $(LIBFREETYPE_CFLAGS) $(USER_INCLUDES)

libsplash_la_SOURCES = Splash.cpp SplashBitmap.cpp SplashClip.cpp SplashFTFont.cpp SplashFTFontEngine.cpp \
	SplashFTFontFile.cpp SplashFont.cpp SplashFontEngine.cpp SplashFontFile.cpp SplashFontFileID.cpp \
	SplashPath.cpp SplashPattern.cpp SplashScreen.cpp SplashState.cpp SplashT1Font.cpp \
	SplashT1FontEngine.cpp SplashT1FontFile.cpp SplashXPath.cpp SplashXPathScanner.cpp

noinst_LTLIBRARIES = libsplash.la
